run: prac_compo.cpp PoligonoIrreg.o
	g++ prac_compo.cpp Coordenada.o PoligonoIrreg.o -o prac_compo

Coordenada.o: Coordenada.cpp Coordenada.h
	g++ Coordenada.cpp -c

PoligonoIrreg.o: PoligonoIrreg.cpp PoligonoIrreg.h
	g++ PoligonoIrreg.cpp -c