run: prac_compo.cpp PoligonoIrreg.o
	g++ Coordenada.o PoligonoIrreg.o prac_compo.cpp -o prac_compo

Coordenada.o: Coordenada.cpp Coordenada.h
	g++ Coordenada.cpp -c

PoligonoIrreg.o: PoligonoIrreg.cpp PoligonoIrreg.h
	g++ PoligonoIrreg.cpp -c
